### ISSUE TITLE
What should we call this repo?

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/jupyter-book-DEPRECATED#1]
As this repo will hold *just* the textbook layout etc for a textbook with Jupyter, perhaps we should use a more generic title for the repo.

A few ideas:

1. Jupyter Textbook
2. Jekyll Textbook
3. Jupyter Books
4. Jekyll Books

cc @samlau95, any thoughts?

**Comment by SamLau95** [comment]
I'm leaning towards something similar to Jupyter Books. I think the name should have Jupyter instead of Jekyll since the project addresses people who use Jupyter.

**Comment by choldgraf** [comment]
Makes sense to me - the main reason I was thinking just "jekyll books" was that you could theoretically just use this template to host a book with Jekyll and only markdown files...but I agree the main point is Jupyter stuff

**Comment by choldgraf** [comment]
going with "jupyter book" for the repo and the guide is called the "Jupyter Books Guide". That sound OK to you? Feel free to reopen if you'd like to discuss more!
