### ISSUE TITLE
Add one more sub-section level in the sidebar

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/jupyter-book-DEPRECATED#12]
Many books have 3 subsections (chapters -> sections -> sub-sections). We could add support for one more in a relatively straightforward fashion, I believe. What do folks think?

**Comment by SamLau95** [comment]
I think this makes sense. Are sub-sections pieces of a page (e.g. https://bookdown.org/yihui/bookdown/markdown-syntax.html#inline-formatting)?

Or sub-sections separate pages entirely?

**Comment by choldgraf** [comment]
ah I see - I meant entirely different pages (the sidebar to the right can handle within-page sections)...this is now demoed here: https://predictablynoisy.com/jupyter-book/ch/01/3/subsection/subsections

**Comment by choldgraf** [comment]
this is in master now!
