### ISSUE TITLE
Should the TOC links point to /notebooks or to /ch

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/jupyter-book-DEPRECATED#14]
Currently the TOC links point to /ch, which is where the converted notebooks will be placed. However, this is a bit unintuitive as it requires the person understand *where* the pages will go, not where they are now.

The old version of this repo had the TOC links go to /notebooks, and this was auto-converted to /ch at build. Is that a better solution? Otherwise, we need to document the /ch behavior

**Comment by SamLau95** [comment]
What might make sense is to replicate the folder hierarchy in `notebooks/` into the root of the project.

For example, having:

```
jupyter-book/
  notebooks/
    ch/
      01/
      02/
      03/
```

Would output:

```
jupyter-book/
  ch/
    01/
    02/
    03/
```

(Note that the underscore is removed. Jekyll will build the `ch/` folder as it does now but without requiring a hardcoded `collections` key in `_config.yml`. This means that if the user has a `notebook/chapters/intro.ipynb` file, the resulting URL will be `mybook.com/chapters/intro.html`.)

This implies that:

```
jupyter-book/
  notebooks/
    ch/
      01/
      02/
    appendix/
      mypage.ipynb
```

Would output:

```
jupyter-book/
  ch/
    01/
    02/
    03/
  appendix/
    mypage.ipynb
```

Pros:

- Avoids having to remember the hard-coded `ch/` value.
- More flexible; if someone wants to have `mybook.com/chapters/one/` they can.

Cons:

- The root folder of the project will contain extra autogenerated folders, one for each direct child of `notebooks/`
- The user still has to remember to remove the `notebooks/` prefix in `toc.yml`.
- The user still has to remember to convert `.ipynb` into `.html` in `toc.yml`.

This might tackle the issue of having multiple textbook sections in one site (https://github.com/choldgraf/jupyter-book/issues/17).

**Comment by choldgraf** [comment]
that's a cool idea - what if instead of the root folder, it went into `/book`? That should keep the auto-generated folders to 1 at the top level

**Comment by SamLau95** [comment]
That sounds like a good idea to me. I'd prefer to have URLs that look like:

    mybook.com/chapter/01/hello.html

Instead of

    mybook.com/book/chapter/01/hello.html

Which is what Jekyll will default to if we use a `book/` folder. Is there a way to get around this?

**Comment by choldgraf** [comment]
actually we should be able to generate the URL of each page in the YAML header, maybe that'd work?

**Comment by SamLau95** [comment]
Oh right. That seems like a good idea!

If we use Jekyll permalinks, should we also remove the .html at the end of the URL?

**Comment by choldgraf** [comment]
I'm +1 on that. So how does this sound for a final design from a user's perspective:

* All notebooks etc are still placed in the `notebooks/` folder.
* In the site build, any children of that folder will have a permalink generated that simply removes the `notebooks/` part of the path. 
	* So if in `toc.yml` an item points to `url: /notebooks/myfolder/myfile.ipynb`, the resulting url in the yaml header will be "permalink: /myfolder/myfile`
* The outputs will *still* go in a folder called "ch", but the "ch" will no longer be a part of the link. (**maybe here we should call the folder something different, like "build" to make it clear that this is auto-generated content?**)
* The TOC etc is still constructed the same way it was before.

Does that sound right?

**Comment by SamLau95** [comment]
Yup, that sounds great.

I think something like `built`, `converted`, or `generated` makes sense.

**Comment by choldgraf** [comment]
wooo! 🎉
