### ISSUE TITLE
Deprecating the guide and moving it into this repo

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/jupyter-book-DEPRECATED#16]
I just realized that we could duplicate the deployment guide by just putting it in a sub-folder of `notebooks/`. Then it shows up in the sidebar like everything else, and we don't have to maintain a totally separate Jekyll repository.

So, I copied all of the guide files into `notebooks/guide` and updated the sidebar to reflect this. Unless people think it's a bad idea, I'm going to deprecate the `jupyter-book-guide` repository, since I think that's unnecessary complexity to add just so we can have 6 markdown pages with instructions on them.

**Comment by SamLau95** [comment]
Makes sense to me! I think having fewer URLs is less confusing.

**Comment by choldgraf** [comment]
cool 👍
