### ISSUE TITLE
Having Multiple Textbook Sections on One Site

### ISSUE THREAD

**Issue by TomDonoghue** [choldgraf/jupyter-book-DEPRECATED#17]
Is there a better / supported way to host multiple 'textbook' components, on the same site? 

As I use this for my class, I want to support multiple, separate collections of notebooks (for course materials, and separately have assignments, etc).

I tried two ways to doing this:
-  generate multiple textbook parts, from the same site. I tried just changing the source and output directories in 'generate_textbook' - but I couldn't get this to actually work using a directory other than _chapters, and I think there would be some work for the SUMMARY.md file, etc. This is what I'd like to do, but haven't yet dug down into doing it. 
- Have multiple actual repositories that generate multiple textbooks, and add links between them
^Currently, this is working and done by having base site from 'https://github.com/COGS18/COGS18.github.io', and linking to another textbook hosted from 'https://github.com/COGS18/Assignments' and so on - but this doesn't seem totally ideal, and leads to extra embedding. 

(Related to this - I also added a config to specific the link name that gets added to the masthead - so that I could rename the link to the textbook portion - and this is a nice small thing I would recommend adding in.)

**Comment by choldgraf** [comment]
Hmmm - could you just host them as multiple "chapters" within the same book? E.g. we could add support for "section headers" in the sidebar, then collections of chapters (specified in `toc.yaml`) underneath

**Comment by TomDonoghue** [comment]
Yeh, I could do that. 

My use case might be a bit weird - but they really are pretty different 'components' of the course, and I would prefer them to be in different places really. I'm not sure what the best / most general thing to support would be. 

What I have right now does work pretty well. Only thing is, I can't seem to get the 'textbook only' version working - and this seems to be something I haven't got working, with the landing page in particular, on GitHub pages deployments (and more than just in this 'weird' setup). Are there any known quirks to that setup? I'm using the version from the demo-repo (a bit out of date now, I think).

**Comment by choldgraf** [comment]
@TomDonoghue check the latest version of this repo, we actually simplified that part quite a bit, so the repo is now *just* a textbook, without the option of having a website alongside it. That should simplify the deployments a bit (though it'll require you to update some TOC stuff.)

If you like we can have a quick chat about this! LMK

**Comment by SamLau95** [comment]
@TomDonoghue From what I understand of your question, maybe https://github.com/choldgraf/jupyter-book/issues/14#issuecomment-428378547 will let you accomplish your goal. What do you think?

**Comment by choldgraf** [comment]
@TomDonoghue check out #22 which I think adds this in the way you'd want!
