### ISSUE TITLE
Collapse sidebar sections?

### ISSUE THREAD

**Issue by SamLau95** [choldgraf/jupyter-book-DEPRECATED#2]
I notice that all sections appear in the sidebar:

![screenshot 2018-10-05 13 39 53](https://user-images.githubusercontent.com/2468904/46559120-24a84780-c8a4-11e8-85a5-b708fc74670f.png)

In the Data 100 textbook, only the sections of the current chapter appear in the sidebar. The rest are collapsed since showing all of them gets unwieldy:

![screenshot 2018-10-05 13 40 28](https://user-images.githubusercontent.com/2468904/46559152-3b4e9e80-c8a4-11e8-936f-704abb83fbe8.png)

Should the sidebar sections be collapsed by default? Collapsing makes sense for books with lots of sections while uncollapsing makes sense for books only a few sections.

**Comment by choldgraf** [comment]
oops - I added in a feature to make this an option, then forgot to turn on the option :-)

There's not a config option in `_config.yml` for this. I just turned it on in the latest push
