### ISSUE TITLE
Deprecate this repo, rename it, and merge it into jupyter-book-guide?

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/jupyter-book-DEPRECATED#23]
Even though we've created this new repository and have been working from it, we keep getting questions, issues, etc on the old guide repository: https://github.com/choldgraf/jupyter-book-guide

that one has about 4 times as many stars as this one and seems to be what people are defaulting to because of previous link clicks etc.

What do folks think about:

1. deprecating this repository 
2. Moving the whole codebase into jupyter-book-guide
3. Re-naming that one to `jupyter-book`

Is that more hassle than it's worth? My main concern is that anyone who has forked that repo will have a huge merge hassle. But maybe it's worth it for the sake of keeping things simple in people's mind.

What do folks think? @SamLau95 any thoughts?

**Comment by SamLau95** [comment]
@choldgraf I'm actually +1 on merging this repo into the other. I think having previous links work is important and keeping things simple will help adoption.

**Comment by choldgraf** [comment]
yeah, the nice thing is that previous links will be properly re-directed. OK I'll do this today so we can cut off the confusion sooner than later

**Comment by choldgraf** [comment]
done

**Comment by choldgraf** [comment]
@SamLau95 don't forget to update your remote (not sure if github will try to transfer it somewhere else)
