### ISSUE TITLE
Next/prev page buttons don't always link to the next page

### ISSUE THREAD

**Issue by SamLau95** [choldgraf/jupyter-book-DEPRECATED#3]
Each page has a next/previous page button:

![screenshot 2018-10-05 13 43 11](https://user-images.githubusercontent.com/2468904/46559233-9aacae80-c8a4-11e8-91b3-4fcfb3af4c35.png)

However, the button does not always link to the next page in the book. On https://predictablynoisy.com/jupyter-book/, the next page should be https://predictablynoisy.com/jupyter-book/ch/introduction/intro . However, the link goes to https://predictablynoisy.com/jupyter-book/ch/introduction/markdown instead, skipping a page.

Also, on https://predictablynoisy.com/jupyter-book/ch/introduction/intro , the next page button links to the same page; clicking it doesn't do anything.

**Comment by choldgraf** [comment]
Hmm - so for the root page, that's because the next page is hard-coded in there. One thing we could do is define next/prev based on the order that's in the TOC, however I'm not sure how easy it is to pull that information outta there.

**Comment by SamLau95** [comment]
Oh gotcha! I thought the next page was programmatically generated and there was a bug in a script.
