### ISSUE TITLE
Can we remove Bootstrap CSS/JS?

### ISSUE THREAD

**Issue by SamLau95** [choldgraf/jupyter-book-DEPRECATED#5]
Removing these libraries will save 35kB in page size (5% savings).

I see that you're using a clipboard icon from font-awesome to add the clipboard button. However, we can instead use a small SVG file (as https://github.com/zenorocha/clipboard.js/ uses), or a Unicode character (https://stackoverflow.com/questions/8714969/is-there-a-unicode-character-for-copy-and-paste)

**Comment by choldgraf** [comment]
Yep, I'm definitely +1 to this. It's a hacky solution and we should definitely not have to import all of bootstrap / FA just for these tiny features :-)

IIRC, the bootstrap is for the "tooltip" that shows up briefly after you click the copy button. The FA icon is a pretty straightforward fix.
